services:
  web:
    image: ghcr.io/nicanordlc/coolify-nginx-reverse-proxy:latest
    build:
      context: .
      platforms:
        - "linux/amd64"
        - "linux/arm64"
      tags:
        - "ghcr.io/nicanordlc/coolify-nginx-reverse-proxy:latest"
      labels:
        org.opencontainers.image.source: https://github.com/nicanordlc/coolify-nginx-reverse-proxy
    environment:
      - PROXY_URL=${PROXY_URL:-https://example.com/}
    restart: unless-stopped
