services:
  firebase-proxy:
    build:
      context: .
      tags:
        - "mgscox/coolify-firebase-nginx-reverse-proxy"
      labels:
        org.opencontainers.image.source: https://github.com/mgscox/coolify-firebase-nginx-reverse-proxy
    environment:
      - FIREBASE_ID=${FIREBASE_ID}
    restart: unless-stopped
